<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/RemixAPI.cs" Link="RemixAPI.cs" />
    <Compile Include="../../src/RemixAPI.Compatibility.cs" Link="RemixAPI.Compatibility.cs" />
  </ItemGroup>
</Project>
